DROP TABLE MEMBER;
DROP TABLE BUSINESS_USER;
DROP TABLE BUSINESS_FILE;
DROP TABLE NON_USER;
DROP TABLE CANCELLATION;
DROP TABLE CART;
DROP TABLE WISHLIST;
DROP TABLE EVENT;
DROP TABLE EVENT_ATTACHMENT;
DROP TABLE USER_CANCEL_BRIDGE;
DROP TABLE NON_USER_CANCEL_BRIDGE;

DROP SEQUENCE SEQ_UNO;      -- 회원 정보
DROP SEQUENCE SEQ_BUNO;     -- 사업자 회원 정보
DROP SEQUENCE SEQ_BFNO;     -- 사업자 파일 정보
DROP SEQUENCE SEQ_RNO;      -- 비회원 예약 번호
DROP SEQUENCE SEQ_CNO;      -- 예약 취소 번호
DROP SEQUENCE SEQ_ENO;      -- 이벤트 게시판 글 번호
DROP SEQUENCE SEQ_EFNO;     -- 이벤트 이미지 파일 번호

    -- * 참고
    -- 부득이하게 테이블명 모두 수정 => TB_TABLE_NAME
    -- 다른분들 작업하신 테이블 참조하는 코드 주석되어 있음

-------------------- MEMBER (회원 정보) ------------------------
CREATE TABLE MEMBER(
    USER_NO     NUMBER PRIMARY KEY,
    USER_ID     VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD    VARCHAR2(100) NOT NULL,
    USER_NAME   VARCHAR2(30) NOT NULL,
    EMAIL       VARCHAR2(30) NOT NULL UNIQUE,
    PHONE       NUMBER NOT NULL,
    SPAM        CHAR(1) DEFAULT 1 CHECK (SPAM IN(1, 0)),
    STATUS      CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_UNO;

--------------------- BUSINESS_USER(사업자 회원) ----------------------
CREATE TABLE BUSINESS_USER(
    BIZ_NO      NUMBER PRIMARY KEY,
    BIZ_NAME    VARCHAR2(30) NOT NULL,
    BIZ_FILENO  NUMBER NOT NULL UNIQUE,
    USER_NO     NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
CREATE SEQUENCE SEQ_BUNO;

--------------------- BUSINESS_FILE (사업자 등록증 파일) ------------------------
CREATE TABLE BUSINESS_FILE(
    FILE_NO     NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(100) NOT NULL,
    CHANGE_NAME VARCHAR2(300) NOT NULL,
    FILE_PATH   VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE,
    STATUS      CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    BIZ_NO      NUMBER NOT NULL,
    FOREIGN KEY (BIZ_NO) REFERENCES BUSINESS_USER(BIZ_NO)
);
CREATE SEQUENCE SEQ_BFNO;

---------------------- NON_USER (비회원) ---------------------------
CREATE TABLE NON_USER(
    RSV_NO        NUMBER PRIMARY KEY,
    NON_USER_NAME VARCHAR2(30) NOT NULL,
    PHONE         NUMBER NOT NULL,
    RSV_DATE      DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_RNO;

---------------------- CANCELLATION (예약 취소 내역) -------------------------
CREATE TABLE CANCELLATION(
    CANCEL_NO   NUMBER PRIMARY KEY,         -- 식별 번호
    REFUND      NUMBER NOT NULL,            -- 환불 방법 ('10'계좌이체, '20'신용카드)
    ACCOUNT_NO  VARCHAR2(50) NOT NULL,      -- 환불 계좌
    REASON      VARCHAR2(1000) NOT NULL,    -- 취소 사유
    CANCEL_DATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_CNO;

--------------------------- CART (장바구니) ------------------------------------
CREATE TABLE CART(
    USER_NO       NUMBER NOT NULL,
    COUNT_NO      NUMBER DEFAULT '1',
    --ROOM_NO     NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
    --FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ROOM_NO)
);

--------------------- WISHLIST (찜 목록, 회원만 이용 가능) ----------------------
CREATE TABLE WISHLIST(
    USER_NO     NUMBER NOT NULL,
    WISH_DATE   DATE DEFAULT SYSDATE,
    --ROOM_NO     NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
    --FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ROOM_NO)
);
-------------------------- EVENT (이벤트 게시판, 관리자만 글 작성) -------------------
CREATE TABLE EVENT(
    EVENT_NO            NUMBER PRIMARY KEY,
    EVENT_TITLE         VARCHAR2(100) NOT NULL,
    EVENT_WRITER        VARCHAR2(30) NOT NULL,
    EVENT_COUNT         NUMBER DEFAULT 0,
    ENROLL_DATE         DATE DEFAULT SYSDATE,
    STATUS CHAR(1)      DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
    --AD_ID VARCHAR2(15)  NOT NULL,
    --FOREIGN KEY (AD_ID) REFERENCES TB_ADMIN(AD_ID)
);
CREATE SEQUENCE SEQ_ENO;

----------------------- EVENT_ATTACHMENT (이벤트 이미지 파일) -------------------
CREATE TABLE EVENT_ATTACHMENT(
    FILE_NO     NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH   VARCHAR2(1000) NOT NULL,
    STATUS      CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    EVENT_NO    NUMBER NOT NULL,
    FOREIGN KEY (EVENT_NO) REFERENCES EVENT(EVENT_NO)
);
CREATE SEQUENCE SEQ_EFNO;

------------------------- USER_CANCEL_BRIDGE (회원 취소 BRIDGE) --------------------
CREATE TABLE USER_CANCEL_BRIDGE(
    USER_NO     NUMBER NOT NULL,
    CANCEL_NO   NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (CANCEL_NO) REFERENCES CANCELLATION(CANCEL_NO)
);

---------------------- NON_USER_CANCEL_BRIDGE (비회원 취소 BRIDGE) -----------------
CREATE TABLE NON_USER_CANCEL_BRIDGE(
    RSV_NO      NUMBER NOT NULL,
    CANCEL_NO   NUMBER NOT NULL,
    FOREIGN KEY (RSV_NO) REFERENCES NON_USER(RSV_NO),
    FOREIGN KEY (CANCEL_NO) REFERENCES CANCELLATION(CANCEL_NO)
);

COMMIT;
